# Generated by Django 3.2 on 2021-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono cliente'),
        ),
    ]
