# Generated by Django 3.2 on 2021-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0002_auto_20210502_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparato',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aparato',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
